name: Adapt-cdk Backend Seeding
run-name: ${{ github.actor }} pushed an update for env ${{ github.ref_name }}
on:
  push:
    paths: "seed/**"
    branches:
      - "dev"
      - "qa"
      - "uat"
      - "main" # prod
jobs:
  dynamodb-seeding:
    runs-on: ubuntu-latest
    # can use this: ${{ github.ref == 'refs/heads/dev' && 'dev' || github.ref == 'refs/heads/qa' && 'qa' || 'default' }}
    # or github.ref_name, but it requires that the github environment has to be exactly the same as the given branch
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install && npm run build
      - name: Run Seeding script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
          AWS_RESOURCE_UNIQUE_ID: ${{ vars.AWS_RESOURCE_UNIQUE_ID }}
          # "state-custom-glossary.json" or "ceds-generic-glossary.json"
          GLOSSARY_TERMS: ${{ vars.GLOSSARY_TERMS }}
        run: node ./seed/seed.js

      - run: echo "This job's status is ${{ job.status }}."
