name: ADYKE Adapt Backend Deploy
run-name: ${{ github.actor }} pushed an update.
on:
  push:
    branches: ["adyke"]
jobs:
  cdk-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install && npm run build
      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "deploy"
          cdk_stack: "*"
          cdk_args: "--require-approval never"
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
          STAGE: "adyke"
          PUBLIC_VAPID_KEY: ${{ secrets.DEV_PUBLIC_VAPID_KEY }}
          PRIVATE_VAPID_KEY: ${{ secrets.DEV_PRIVATE_VAPID_KEY }}
      - run: echo "This job's status is ${{ job.status }}."
